
site_name: Asymptote
site_url: https://material-didatico.github.io/Asymptote

nav:
  - Início: index.md
theme:
  name:       material
  language:   pt-BR
  custom_dir: docs/overrides

  features:
    - navigation.instant

  font:
    text: "Lato"
    code: "Fira Code"

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true # Enables dollar delimiters for inline math

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - stylesheets/extras.css
